sudo: required

services:
  - docker

addons:
  ssh_known_hosts: 54.36.181.198

script:
  - docker build -t frontend .
  - docker run --rm frontend npm run lint

deploy:
  - provider: script
    script:
      - docker login https://registry.glitchless.ru -u null -p null &&
            docker tag frontend registry.glitchless.ru/rhythm_blast/frontend:latest &&
            docker push registry.glitchless.ru/rhythm_blast/frontend:latest &&
            ssh ansible@54.36.181.198 "cd ansible && ansible-playbook playbook.yml"
    on:
      branch: site-base

before_install:
  - openssl aes-256-cbc -K $encrypted_84b92aa8c331_key -iv $encrypted_84b92aa8c331_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
