language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
- npm run lint
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Zzv/almN56Ms46mDLSwWW/Sg5cgBs/sd2SnJVqMI3iTFV4xmET8v46Vd1sn/KXmYMcYXxmTACN4osvj01aNplN4z6bOJlholjHlEZG7i/4Zalvnxgm63NqGxtdiiomsJuOmVXMx32xZCGQ1483uBa4OddIcBnsxM5iwoyJ3KYWCwteVC4KrsBK42nwe1vPaAtum3No1VCa8jRyTSmAYLatQSF3qvBCTAXvEETh0Sy5MU5i6dMqakHjMUrYoIu4zAuu1K0cUilJ30K2JPLHgIeBO+jlmqmalQrNM1dQW0W4GikCftHbB5Sgoxu6LpMOCtyGU4JFoMYeo/hWJ6ZDAFp0BKKDoJDx/MX3ho10XZ8wZETZRULnQnwcR1bQXm7Y13KLSWSdo6fzQuKMISbT3fwxo5pB6ByHgNgJwxIV4RTeCjERgip3VZFqX4saQtPE4XIL3uJ6FEKTrvqT3iGnhS3Bu4ye317/Fh9jGOuSbYAkeOPkJSeUN55mBiQw0Qb0vHJfVd0ORIDXCpNGVfjHXT7II39X40gYzDm6JobRxMDklLu5JjE6otkZ694suF9usNm9Mh+hZ0uHg8+v+R6OEn5WfbDoulVkP4hzabOCZSxIMKZBj4XCSCAhPfValbUDWQ2vB1VRfdilOAVaQexj8nLW9SdhHiagDmB9OFivoeYzY=
  app: glitchless
  on:
    repo: frontend-park-mail-ru/2017_2_glitchless
    branch: site-base
